- .claude-guidelines.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation_improvement.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/project_setup_guide.md
- .github/workflows/claude-issue-triage.yml
- .github/workflows/claude-lint.yml
- .gitignore
- lint.md
- test-code.js
- triage.md
Testing the Claude lint workflow with intentional style issues in test-code.js to see if Claude catches them:
- Using enum instead of union types
- Using three dots (...) instead of Unicode ellipsis (…)
- Using var instead of const/let
This should trigger the claude-lint.yml workflow.
> Test: Claude lint workflow

- data/anti_patterns.json
- data/cognee_case_study.json
- docs/Product_Requirements_Document.md
- docs/Technical_Implementation_Guide.md
- requirements_phase0.txt
- validation/README.md
- validation/VALIDATION_RESULTS.md
- validation/comprehensive_test.py
- validation/detect_patterns.py
- validation/sample_code/bad_examples.py
- validation/sample_code/cognee_failure.py
- validation/sample_code/good_examples.py
Completes Phase 0 validation of core anti-pattern detection algorithms, addressing the Infrastructure-Without-Implementation anti-pattern identified in the technical review. This validation-first approach proves detection works BEFORE building any server infrastructure.
- **100% accuracy** on core validation tests (7/7 passed)
- **87.5% accuracy** on comprehensive sample tests (7/8 passed)
- **0% false positive rate** on good architectural decisions
- **Cognee failure case** detected with 100% confidence and correct evidence
- **Sub-second performance** for all detection operations
This implementation directly applies our own anti-pattern prevention guidelines:
✅ **Documentation-First**: Researched detection approaches before implementation  
✅ **Validation-Driven**: Proved algorithms …
> Feature: Phase 0 Anti-Pattern Detection Validation Complete

- requirements_phase1.txt
- src/anti_pattern_coach/cli.py
- src/anti_pattern_coach/core/pattern_detector.py
Completes Phase 1.1 implementation of the core PatternDetector class using validated algorithms from Phase 0. This creates a structured, class-based architecture for anti-pattern detection while maintaining the 87.5%+ accuracy achieved in validation.
- **Core Detection Engine**: Implemented `PatternDetector` class with `analyze_text_for_patterns()` method
- **Multi-Pattern Support**: All 4 anti-pattern types (infrastructure, symptom-driven, complexity, documentation)  
- **Educational Content**: WHY explanations, case studies, and remediation guidance for each detected pattern
- **100% Validation**: Cognee case + good case + all pattern types working correctly
- **Zero Dependencies**: Pure Python standard library implementation
- `analyze_text_for_patterns()` - Main detection method using …
> Feature: Phase 1.1 Core PatternDetector Implementation Complete

- src/anti_pattern_coach/core/educational_content.py
- src/anti_pattern_coach/core/pattern_detector.py
- ✅ **Enhanced Educational Content System**: Created comprehensive `EducationalContentGenerator` class with multi-level educational responses
- ✅ **Detail Level Support**: Implemented Brief, Standard, and Comprehensive detail levels for different use cases  
- ✅ **Cognee Case Study Integration**: Enhanced real-world case study integration with structured data
- ✅ **Comprehensive Educational Responses**: Added WHY explanations, impact assessments, immediate actions, remediation steps, prevention checklists, related examples, learning resources, and best practices
- ✅ **Backward Compatibility**: Maintained existing API while significantly enhancing educational value
✅ **Pattern Detection Accuracy**: 100% maintained (all 4 pattern types detected correctly)  
✅ **Cognee Case Study**: …
> Feature: Enhanced Educational Content System #10

- data/pattern_schema.json
- docs/PATTERN_DEFINITIONS.md
- docs/PATTERN_WEIGHT_METHODOLOGY.md
- docs/Technical_Implementation_Guide.md
- src/anti_pattern_coach/utils/__init__.py
- src/anti_pattern_coach/utils/pattern_validator.py
- validation/weight_calibration_results.json
Implements comprehensive documentation and validation system for anti-pattern definitions, significantly improving maintainability and supporting future pattern development.
- **Resolves #18**: Pattern definition JSON schema documentation
- **Resolves #14**: Regex weight determination methodology documentation
- **87.5%** detection accuracy (target: >80%) ✅
- **0%** false positive rate (target: <10%) ✅  
- **100%** precision (all detections correct) ✅
- **0.933** F1 score (excellent balance) ✅
- Complete schema definition for all pattern fields
- Validation rules and constraints for required/optional properties
- Type safety and value range enforcement
- ✅ All current patterns validate successfully
- Detailed field explanations and usage guidelines
- Weight calibration methodology with …
> Feature: Comprehensive Pattern Definition Documentation & Validation System

- .gitignore
- requirements.txt
- requirements_phase0.txt
- requirements_phase1.txt
- src/anti_pattern_coach/__init__.py
- src/anti_pattern_coach/__main__.py
- src/anti_pattern_coach/server.py
- src/anti_pattern_coach/tools/__init__.py
- src/anti_pattern_coach/tools/demo_tool.py
- tests/test_mcp_server.py
Implements complete FastMCP server entry point with validated core engine integration, fulfilling Issue #21 requirements.
- **Server Entry Point**: `src/anti_pattern_coach/server.py` with FastMCP initialization
- **Tool Registration**: Auto-discovery and registration of MCP tools via decorators
- **Module Support**: Full `python -m anti_pattern_coach.server` support
- **Error Handling**: Graceful startup/shutdown with proper logging
- **Demo Tools**: `analyze_text_demo` and `server_status` tools using validated Phase 1 engine
- **Pattern Detection**: Full integration with PatternDetector (87.5% accuracy, 0% false positives)
- **Educational Content**: Integration with EducationalContentGenerator for comprehensive responses
- **JSON Serialization**: Proper conversion of dataclass results …
> Feature: Phase 2.1 FastMCP Server Entry Point Implementation

- .gitignore
- src/vibe_compass/server.py
- src/vibe_compass/tools/analyze_issue.py
• Implements the `analyze_github_issue` MCP tool that fetches GitHub issues and analyzes them for anti-patterns using the proven core detection engine
• Creates comprehensive `GitHubIssueAnalyzer` class with GitHub API integration, PatternDetector, and EducationalContentGenerator
• **New File**: `src/vibe_compass/tools/analyze_issue.py` - Complete GitHub Issue Analysis implementation
• **Enhanced**: `src/vibe_compass/server.py` - Added `analyze_github_issue` FastMCP tool integration
• **Dependencies**: PyGithub integration for robust GitHub API handling
• **Error Handling**: Comprehensive error handling for GitHub API failures and invalid parameters
• **Testing**: Verified with real GitHub issues and pattern detection validation
• Supports `issue_number`, `repository` (optional), …
> Feature: GitHub Issue Analysis MCP Tool #22

- tests/test_timing_utils.py
- validation/PERFORMANCE_BENCHMARKS.md
- validation/comprehensive_test.py
- validation/detect_patterns.py
- validation/timing_utils.py
Fixes #16. Adds performance timing measurements to validation scripts for better performance monitoring and regression detection.
> Enhancement: Add performance timing to validation output (#16)

- data/anti_patterns.json
- data/pattern_schema.json
- src/vibe_compass/core/pattern_detector.py
- src/vibe_compass/utils/version_utils.py
- tests/test_pattern_versioning.py
- validation/detect_patterns.py
Fixes #15. Implements comprehensive pattern versioning system for anti_patterns.json enabling pattern evolution tracking, compatibility management, and migration support.
- **Global versioning**: schema_version (1.1.0) and data_version (1.0.0) at database level
- **Pattern-level versioning**: Individual pattern versions (1.0.0) for granular tracking
- **Semantic versioning**: MAJOR.MINOR.PATCH format with proper validation
- ✅ **Full backward compatibility**: Existing code works without modifications
- ✅ **Schema validation**: Version fields validated with regex patterns
- ✅ **Detection integration**: Pattern versions included in detection results  
- ✅ **Version utilities**: Parsing, comparison, and migration guidance tools
- ✅ **Comprehensive testing**: 14 tests covering all versioning …
> Enhancement: Add pattern versioning to anti_patterns.json (#15)

- docs/USAGE.md
- src/vibe_check/cli.py
- src/vibe_check/server.py
- src/vibe_check/tools/pr_review.py
- test_pr_review.py
🎉 **Complete implementation of comprehensive PR review MCP tool that replicates ALL 731 lines of functionality from scripts/review-pr.sh**
Fixes #35 (PR Review MCP Tool Implementation)
- **Multi-dimensional PR size classification**: Lines, files, character-based sizing with intelligent strategies
- **Re-review detection and tracking**: Automatic detection, progress assessment, context-aware analysis  
- **Linked issue analysis and validation**: Full PR-issue alignment verification with GitHub integration
- **Comprehensive GitHub integration**: Comment posting, label management, permanent logging
- **Clear-Thought integration points**: Ready for systematic analysis enhancement (as requested)
- **Enterprise error handling**: Graceful fallbacks, timeout management, comprehensive logging
- …
> Feature: Comprehensive PR Review MCP Tool - Complete Implementation #35

- .gitignore
- src/vibe_check/server.py
- src/vibe_check/tools/pr_review.py
- src/vibe_check/tools/test_claude_cli.py
- src/vibe_check/tools/vibe_check_framework.py
- Add comprehensive MCP test suite for Claude CLI integration verification
- Implement 6 specialized test tools to diagnose Claude CLI integration issues
- Update gitignore to prevent recursive directory structures
1. **test_claude_cli_availability**: Check if Claude CLI is installed and get version
2. **test_claude_cli_integration**: Core integration test with enhanced diagnostics  
3. **test_claude_cli_with_file_input**: Test file-based input handling
4. **test_claude_cli_comprehensive**: Multi-scenario test suite
5. **test_claude_cli_mcp_permissions**: Test MCP permissions bypass functionality
6. **test_claude_cli_recursion_detection**: Detect and diagnose recursion risks
- ThreadPoolExecutor implementation to prevent async subprocess crashes
- Comprehensive timeout and error handling …
> Feature: Add comprehensive Claude CLI integration test tools

- src/vibe_check/server.py
- src/vibe_check/tools/external_claude_cli.py
- src/vibe_check/tools/external_claude_integration.py
- Implement comprehensive external Claude CLI integration solution
- Solve MCP server context blocking issues through isolated subprocess execution
- Follow Claude Code SDK best practices with JSON output and system prompts
- Provide specialized analysis tools for PR review, code analysis, and issue analysis
Resolves timeout issues when calling `claude -p` from within MCP server context (Issue #57). Previous attempts to call Claude CLI from MCP tools resulted in 30-second timeouts due to context blocking. External subprocess execution completely eliminates this issue.
**Systematic Analysis Used:**
- ✅ **Decision Framework**: Confirmed external subprocess approach is optimal over Docker/separate server alternatives
- ✅ **Mental Model (First Principles)**: Validated architecture addresses …
> Feature: External Claude CLI integration with SDK best practices

- README.md
- docs/Technical_Implementation_Guide.md
- docs/USAGE.md
- src/vibe_check/tools/external_claude_cli.py
- src/vibe_check/tools/external_claude_integration.py
- tests/integration/test_external_claude_integration.py
- tests/unit/test_external_claude_cli.py
- tests/unit/test_external_claude_integration.py
- tests/unit/test_pr_review_external_claude.py
- **Complete Phase 3 validation** for external Claude CLI integration from Issue #57
- **Independent Claude session architecture** successfully implemented and tested
- **Comprehensive test coverage** with 78 test cases across integration and unit testing
- **Fixed critical MCP server loading issue** and all test failures systematically
1. **Independent Context Windows**: PR reviews and code analysis don't consume main conversation tokens
2. **Parallel Processing**: Multiple Claude CLI tasks can run simultaneously  
3. **Specialized Prompts**: Each task type gets optimized system prompts
4. **No Timeout Issues**: External Claude CLI calls complete successfully
5. **Anti-pattern Prevention**: System validates against recursive execution patterns
- **Fixed MCP Server Loading**: Added …
> Feature: Complete external Claude CLI integration with comprehensive testing (Issue #57)

- src/vibe_check/tools/test_claude_cli.py
Successfully migrated the test_claude_cli_integration() tool from direct subprocess calls to the proven ExternalClaudeCli wrapper architecture, resolving Issue #63.
- **Replaced subprocess calls**: Eliminated problematic direct Claude CLI subprocess execution
- **Added external wrapper integration**: Now uses ExternalClaudeCli.analyze_content() for timeout-safe execution
- **Enhanced response model**: Added wrapper-specific fields (cost_usd, session_id, uses_external_wrapper)
- **Task type support**: Added task_type parameter for specialized system prompts
- **Cleaned up duplicate code**: Removed 149 lines of obsolete subprocess implementation
- **Enhanced error handling**: Comprehensive exception handling for external wrapper failures
- **Improved diagnostics**: Added external wrapper …
> Feature: Migrate test_claude_cli_integration to ExternalClaudeCli wrapper (#63)

- src/vibe_check/tools/shared/circuit_breaker.py
- src/vibe_check/tools/shared/claude_integration.py
- src/vibe_check/tools/shared/health_monitor.py
- src/vibe_check/tools/shared/retry_logic.py
- tests/unit/test_circuit_breaker.py
This PR implements **Phase 2** of the reliability overhaul for vibe-check-mcp, introducing a comprehensive circuit breaker pattern to handle Claude CLI failures gracefully.
- **Circuit Breaker**: CLOSED/OPEN/HALF_OPEN states with automatic recovery
- **Retry Logic**: Exponential backoff with intelligent failure handling
- **Health Monitoring**: Real-time performance metrics and diagnostics  
- **Integration**: Backward compatible enhancement of existing Claude CLI tools
- ✅ Configurable failure thresholds and recovery timeouts
- ✅ Real-time health assessment with scoring and issue detection
- ✅ Multiple retry strategies (exponential, linear, fixed backoff)
- ✅ Graceful degradation preventing cascading system failures
- ✅ Detailed performance metrics and trend analysis
- ✅ Comprehensive …
> Feature: Circuit breaker pattern for Claude CLI reliability (Issue #102)

- src/vibe_check/tools/analyze_llm/specialized_analyzers.py
- src/vibe_check/tools/analyze_llm/tool_registry.py
- src/vibe_check/tools/async_analysis/__init__.py
- src/vibe_check/tools/async_analysis/config.py
- src/vibe_check/tools/async_analysis/integration.py
- src/vibe_check/tools/async_analysis/queue_manager.py
- src/vibe_check/tools/async_analysis/status_tracker.py
- src/vibe_check/tools/async_analysis/worker.py
- tests/integration/test_async_analysis_integration.py
- tests/unit/test_async_analysis.py
This PR implements **Phase 4** of the reliability overhaul - async processing queue for massive PRs that exceed all analysis thresholds, achieving **100% PR coverage** with intelligent four-tier analysis strategy.
Previously, massive PRs (>1500 lines, >30 files) were skipped entirely with only basic pattern analysis. Examples:
- PR 660: 2,908 lines, 6 files (V1-V2 testing framework)
- PR 692: 76 files, 20,275 total changes (complete V2 TXT generation)
These complex architectural changes would benefit most from LLM analysis but were impossible to analyze.
| PR Size | Lines | Files | Strategy | Implementation |
|---------|-------|-------|----------|----------------|
| **SMALL** | ≤500 | ≤10 | Full LLM analysis | ✅ Phase 1 |
| **MEDIUM** | 500-1000 | 10-20 | Chunked LLM analysis | ✅ Phase 3 …
> Feature: Phase 4 - Async processing queue for massive PRs (Issue #104)

- data/integration_knowledge_base.json
- docs/USAGE.md
- src/vibe_check/server.py
- src/vibe_check/tools/analyze_llm/tool_registry.py
- src/vibe_check/tools/async_analysis/graceful_degradation.py
- src/vibe_check/tools/async_analysis/health_monitoring.py
- src/vibe_check/tools/async_analysis/integration.py
- src/vibe_check/tools/async_analysis/queue_manager.py
- src/vibe_check/tools/async_analysis/resource_monitor.py
- src/vibe_check/tools/async_analysis/validation.py
- src/vibe_check/tools/async_analysis/worker.py
- src/vibe_check/tools/integration_decision_check.py
- src/vibe_check/tools/web_search_integration.py
- tests/integration/test_async_analysis_real_github.py
- tests/integration/test_integration_decision_workflow.py
- tests/unit/test_integration_decision_check.py
- tests/unit/test_issue_110_improvements.py
Implements comprehensive integration decision checking mechanism to prevent unnecessary custom development. Based on real-world case studies including the Cognee integration failure where 2+ weeks were spent building custom REST servers instead of using the official Docker container.
- **`check_integration_alternatives`**: Validates integration approaches against official solutions
- **`analyze_integration_decision_text`**: Detects integration anti-patterns in text content  
- **`integration_decision_framework`**: Structured decision analysis with Clear Thought integration
- **7 Popular Technologies**: Cognee, Supabase, Claude, OpenAI, GitHub, Docker, Kubernetes
- **Red Flag Detection**: Custom REST servers, manual auth, custom HTTP clients, environment forcing
- **Official Solution …
> [P1][Feature]: Official Alternative Check for Integration Decisions (Issue #113)

- data/anti_patterns.json
- docs/USAGE.md
- src/vibe_check/core/integration_pattern_detector.py
- src/vibe_check/server.py
- src/vibe_check/tools/analyze_llm/specialized_analyzers.py
- src/vibe_check/tools/integration_pattern_analysis.py
- tests/unit/test_integration_pattern_detector.py
- ✅ **Real-time Integration Pattern Detection**: Sub-second technology recognition and anti-pattern detection
- ✅ **Technology Coverage**: Cognee, Supabase, OpenAI, Claude, GitHub, Docker, Kubernetes
- ✅ **Red Flag Detection**: Custom development when official alternatives exist
- ✅ **MCP Tool Integration**: 3 new tools for seamless development workflow integration
- ✅ **Enhanced LLM Analysis**: Existing tools now include integration pattern awareness
- **IntegrationPatternDetector**: Core detection engine with technology recognition
- **Real-time MCP Tools**: `analyze_integration_patterns`, `quick_tech_scan`, `analyze_integration_effort`
- **Enhanced Pattern Data**: Added integration-specific patterns to `anti_patterns.json`
- **LLM Enhancement**: Existing issue/PR analysis tools now …
> Feature: Integration Pattern Detection for Vibe Coding Safety Net (Issue #112)

- src/vibe_check/server.py
- src/vibe_check/tools/pr_review/claude_integration.py
- src/vibe_check/tools/pr_review/file_type_analyzer.py
- src/vibe_check/tools/pr_review/main.py
- tests/test_enhanced_pr_review.py
This PR enhances the PR review tool with file type-specific analysis, author-aware feedback, and model selection capabilities, inspired by Claude GitHub action patterns.
- Created `FileTypeAnalyzer` class that detects and categorizes files
- Provides specialized review guidelines for:
- **TypeScript/JavaScript**: Type safety, modern syntax, async patterns
- **Python**: Type hints, PEP 8 compliance, exception handling  
- **API Endpoints**: Security, input validation, rate limiting
- **React Components**: Performance, accessibility, hooks
- **Tests**: Coverage, edge cases, test quality
- **Config/SQL**: Security-sensitive reviews
- Detects first-time contributors via `author_association`
- Provides encouraging and detailed feedback for newcomers
- Adjusts review tone based on contributor …
> feat: enhance PR review with file type analysis and model selection

- src/vibe_check/server.py
Resolves #151 - PR vibe checks were only analyzing titles/descriptions, never the actual code changes!
**Before this fix:**
- `vibe_check_mentor` function analyzed only `query + context` 
- When asked about PRs, it only saw title/description
- **Never fetched or analyzed actual diff content**
- Missing critical code pattern detection in real changes
**Enhanced PR Detection & Diff Fetching:**
- Detects PR references: `PR #123`, `pull request 456` 
- Automatically fetches actual GitHub diff using GitHub abstraction layer
- Includes real code changes in pattern analysis
- Maintains backward compatibility for non-PR queries
**Key Features:**
- 🎯 Minimal, surgical fix - only 29 lines added
- 🔍 Regex-based PR detection for multiple formats
- 🐙 Uses existing GitHub abstraction layer
- ⚡ Graceful …
> [Bug]: Fix PR diff analysis in vibe_check_mentor - resolves #151

- src/vibe_check/config/tech_patterns.yaml
- src/vibe_check/core/architectural_concept_detector.py
- src/vibe_check/core/code_reference_extractor.py
- src/vibe_check/tools/analyze_issue_nollm.py
- tests/test_architectural_concept_detector.py
- tests/test_architectural_integration.py
- tests/unit/test_code_reference_extractor.py
$(cat <<'EOF'
Implements Issue #155 with the MVP approach recommended by vibe check mentor consultation. Transforms issue analysis from "file-aware" to "architecture-aware" by detecting architectural concepts in natural language.
- **Architectural Concept Detection**: Automatically detects auth, payment, API, database, and caching concepts from issue descriptions
- **Smart File Discovery**: Provides GitHub search queries and file patterns for finding relevant implementation files  
- **Architecture-Aware Recommendations**: Context-specific guidance based on detected architectural focus
**Before** (Issue: "Authentication system is slow"):
- Generic performance tips
- Generic authentication best practices
**After** (Same Issue):
- ✅ Detected `authentication` architectural focus (confidence: …
> [Enhancement]: Architecture-aware issue analysis with conceptual detection - Issue #155

- src/vibe_check/server.py
- src/vibe_check/tools/large_prompt_demo.py
- src/vibe_check/tools/large_prompt_handler.py
- test_configurable_limit.py
- test_large_prompt_integration.py
- test_large_prompt_simple.py
$(cat <<'EOF'
Implements a simple, elegant solution for MCP token limit bypass inspired by Zen MCP server. This replaces the overengineered approach from PR #157 (473 lines) with a minimal ~100-line implementation.
- **Simple character-based detection**: 50K character threshold
- **File-based fallback**: When content exceeds limits, Claude saves to file
- **Native Claude integration**: Leverages Claude's built-in file handling
- **FastMCP integration**: Proper @mcp.tool() decorator usage
1. **`large_prompt_handler.py`**: Core detection and file handling logic
2. **`large_prompt_demo.py`**: Demo tool showing the approach in action  
3. **Server integration**: Added `demo_large_prompt_handling` MCP tool
4. **Comprehensive testing**: Unit and integration tests (7 tests passing)
- ❌ …
> feat: Zen-style large prompt handling for MCP token limit bypass

- src/vibe_check/server.py
- src/vibe_check/tools/large_prompt_demo.py
- src/vibe_check/tools/large_prompt_handler.py
- src/vibe_check/tools/vibe_mentor.py
- test_configurable_limit.py
- test_large_prompt_integration.py
- test_large_prompt_simple.py
$(cat <<'EOF'
Fixes issue #163 by resolving two critical bugs in the vibe_check_mentor tool that were causing pattern detection failures and runtime errors.
- **Problem**: `vibe_check_mentor` looked for "detected_patterns" field, but `analyze_text_demo` returns "patterns"
- **Solution**: Updated field access to use correct "patterns" field
- **Impact**: Eliminates confidence: 0 failures and enables proper pattern detection
- **Problem**: Multiple files referenced `ConfidenceScores.MEDIUM` but it didn't exist
- **Solution**: Added `MEDIUM = 0.78` to ConfidenceScores class
- **Impact**: Eliminates AttributeError crashes in response strategies
- **Problem**: Zero visibility into why pattern detection failed
- **Solution**: Added debug logging for pattern counts, confidence levels, and …
> [Bug Fix]: Resolve vibe_check_mentor pattern detection failures - fixes #163

- .vibe-check/config.json
- .vibe-check/library-context.json
- .vibe-check/pattern-exceptions.json
- data/integration_knowledge_base.json
- src/vibe_check/config/vibe_check_config.py
- src/vibe_check/mentor/response/coordinator.py
- src/vibe_check/mentor/response/generators/ai_engineer.py
- src/vibe_check/mentor/response/generators/base_generator.py
- src/vibe_check/mentor/response/generators/product_engineer.py
- src/vibe_check/mentor/response/generators/senior_engineer.py
- src/vibe_check/server.py
- src/vibe_check/tools/analyze_text_nollm.py
- src/vibe_check/tools/contextual_documentation.py
- src/vibe_check/tools/vibe_mentor.py
Implements contextual documentation loading system to make vibe-check analysis project-aware instead of giving generic advice. This addresses Issue #168 by creating a 3-layer contextual system that detects project libraries, parses documentation, and provides library-specific recommendations.
- **LibraryDetectionEngine**: Scans project files for library usage patterns
- **Multi-language support**: Python, JavaScript, TypeScript with extensible patterns
- **Performance optimized**: 1000 file limit, 30s timeout, caching
- **Confidence scoring**: Weighted detection based on imports, dependencies, file patterns
- **AnalysisContext**: Unified context object with library docs and project conventions
- **ProjectDocumentationParser**: Extracts context from README, CONTRIBUTING, ARCHITECTURE.md
- …
> feat: Implement contextual documentation loading for project-aware analysis (Issue #168)

- benchmarks/performance_optimization_report.md
- benchmarks/security_performance_benchmark.py
- benchmarks/simple_security_benchmark.py
- docs/SECURITY.md
- src/vibe_check/mentor/mcp_sampling_optimized.py
- src/vibe_check/mentor/mcp_sampling_patch.py
- src/vibe_check/mentor/mcp_sampling_ultrafast.py
- src/vibe_check/server.py
- tests/security/README_SECURITY_TESTS.md
- tests/security/test_security_regression.py
- tests/unit/test_educational_content.py
This PR deploys the security fixes that were implemented in PRs #200-203 but never activated in production, addressing 12 security vulnerabilities identified in PR #190.
- PRs #200-203 created security fixes but they were never deployed
- The vulnerable `mcp_sampling.py` is still being imported in production
- Secure implementations (`mcp_sampling_secure.py`) exist but aren't being used
- This is "security theater" - secure code exists but isn't running
1. **Activated security patches** via runtime patching in `server.py` with environment flag control
2. **Optimized performance** from 30% overhead down to 0.02% (19.9x improvement)
3. **Added comprehensive tests** - 17 security regression tests
4. **Added rollback mechanism** via `VIBE_CHECK_SECURITY_PATCHES` environment variable
The …
> fix(security): Deploy critical security fixes from PRs #200-203 with performance optimizations

- benchmarks/mcp_sampling_latency.py
- latency_benchmark_results.txt
- poc_validation_results.txt
- rate_limit_results.txt
- research/MCP_SAMPLING_FINDINGS.md
- research/mcp_poc_validation.py
- research/mcp_rate_limits.py
- research/mcp_streaming_test.py
- streaming_test_results.txt
- tests/integration/test_mentor_mcp_integration.py
Closes #195
Validates approach for #189
Completed focused 1-2 day research phase answering the 4 critical questions needed to validate MCP sampling for dynamic response generation.
1. **Streaming Support**: NO - FastMCP doesn't support it yet (workarounds available)
2. **Latency**: P95 = 1652ms (well under 3s target) ✅
3. **Rate Limits**: No hard limits detected, circuit breaker working ✅
4. **Error Handling**: Fully implemented with circuit breaker, timeouts, fallbacks ✅
```
LATENCY STATISTICS:
P50 (Median): 734.5ms
P95:          1652.2ms  ← Well under 3s target!
P99:          1652.2ms
Mean:         833.7ms
BY CATEGORY:
Simple queries:  265-320ms
Medium queries:  642-753ms
Complex queries: 1441-1652ms
```
Successfully handles the specific query from issue #189:
- Query: "Should I …
> [Research]: Complete MCP sampling research - Issue #195

- README.md
- docs/SECURITY.md
- src/vibe_check/mentor/deprecated/README.md
- src/vibe_check/server.py
**Focused hotfix** addressing code review feedback from PR #211.
Fixes issue #210 where `vibe_check_mentor` fails with:
```
VibeMentorEngine.generate_contribution() got an unexpected keyword argument 'ctx'
```
**Single line fix**:
- **File**: `src/vibe_check/server.py:1618`  
- **Action**: Remove `ctx=ctx` parameter from `engine.generate_contribution()` call
- **Scope**: Bug fix only (no additional features or unrelated changes)
```python
contribution = await engine.generate_contribution(
session=session,
persona=persona,
detected_patterns=detected_patterns,
context=context,
project_context=project_context,
file_contexts=file_contexts,
ctx=ctx  # ❌ Parameter not accepted by method signature
)
```
```python
contribution = await engine.generate_contribution(
session=session, …
```
> fix: Remove unexpected ctx parameter from generate_contribution call

- .gitignore
- src/vibe_check/tools/vibe_mentor.py
- tests/unit/test_vibe_check_mentor.py
$(cat <<'EOF'
Implements **simple test factory pattern** instead of full dependency injection, following collaborative reasoning analysis that concluded full DI would be overengineering for a 1-2 developer team with no current singleton pain.
**✅ What We Built:**
- Simple `create_mentor_engine()` factory function for testing
- `TestMentorEngine` class supporting dependency injection
- Comprehensive test coverage demonstrating new pattern  
- Complete architectural decision documentation
**✅ What We Preserved:**
- Production singleton pattern (zero risk)
- Full backward compatibility 
- Clear upgrade path for future full DI if needed
This implementation directly follows the collaborative reasoning analysis in [Issue #161 comment](https://github.com/kesslerio/vibe-check-mcp/issues/161#issuec …
> feat(mentor): Simple test factory for dependency injection (Issue #161)

- README.md
- data/personas.json
- data/tool_descriptions.json
- scripts/count_tool_tokens.py
- src/vibe_check/__init__.py
- src/vibe_check/server/core.py
- src/vibe_check/server/main.py
- src/vibe_check/server/tools/integration_decisions.py
- src/vibe_check/server/tools/mentor/core.py
- src/vibe_check/server/tools/text_analysis.py
- src/vibe_check/tools/analyze_llm/specialized_analyzers.py
- src/vibe_check/tools/analyze_llm/text_analyzer.py
- src/vibe_check/tools/analyze_llm/tool_registry.py
- src/vibe_check/tools/diagnostics_claude_cli.py
Massive token reduction in MCP tool schemas achieved through documentation externalization and docstring optimization.
MCP tool schemas consumed **~35,402 tokens** for 43 tools (~823 tokens/tool average), representing **17.5% of 200K context window** before any actual work began.
- Reduced available context for actual development work
- Increased latency and cost per request
- Risk of hitting context limits with large codebases
- Standard MCP tools should be 50-300 tokens each, not 800+
- Created `data/tool_descriptions.json` with comprehensive tool documentation
- Created `data/personas.json` with vibe_check_mentor persona configurations
- Externalized verbose descriptions, examples, use cases, and parameters
Systematically trimmed all tool docstrings from verbose multi-paragraph format …
> [Performance]: Reduce MCP tool token consumption by 86.7% (35K → 4.7K)
